import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers";
import { Header } from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type LayoutProps = Readonly<{
	children: React.ReactNode;
}>;

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				<body
					className={`${inter.className} bg-tremor-background dark:bg-dark-tremor-background relative h-screen max-h-screen flex flex-col`}
				>
					<Header />
					<main className="flex flex-col grow mt-header">{children}</main>
				</body>
			</ThemeProvider>
		</html>
	);
};

export default RootLayout;
